version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
   configuration: docs/source/conf.py
